### ISSUE TITLE
Settings (set defaults or sync with YAML)

### ISSUE THREAD

**Issue by jacobmix** [ArchipelaGOAL/Archipelago#27]
### Settings

This for tracking, and discussing settings for both added features, and future ones.
How to handle them in-game, and in the yaml. What the default is, whether to sync from yaml at any point, ect.
Example: Default setting: On/Off, Sync & overwrite on: Never/Newgame/Load (remember setting for save slot or use yaml/server?)
- [x] [Keep vanilla setting between mod updates](https://discord.com/channels/731205301247803413/1138467653552451606/1257388225727823984)
- [x] [Change setting handling to be different. (auto sync per-save slot, ignore save or other)](https://discord.com/channels/731205301247803413/1138467653552451606/1260185632869843084)
- [x] https://github.com/ArchipelaGOAL/Archipelago/issues/20 (Currently to continue a game you have to load a save first. Then connect)
- [x] https://github.com/ArchipelaGOAL/Archipelago/issues/8 (Current: Default: Off. Sync with yaml: First connect)
 - [x] [Sync yaml setting for deathlink to in-game save-slot deathlink setting once when starting new game](https://discord.com/channels/731205301247803413/1138467653552451606/1257379607611703327)
- [x] https://github.com/ArchipelaGOAL/Archipelago/issues/7 (Current: Default: On. Sync with yaml: First connect)
 - [x] [Change move rando in-game setting to be on by default. As setting in yaml will just give you moves anyway if set to no. Making the setting just for players wanting to disable it mid-run since in-game setting just unlocks moves instead of giving movement items. So it's able to be re-enabled as well.](https://discord.com/channels/731205301247803413/1138467653552451606/1257372804672917567)
 - [ ] Expand move rando setting to add goggles (YAML only)
- [x] https://github.com/ArchipelaGOAL/Archipelago/issues/9 (Current: Default: N/A. Sync with yaml: First connect) Discord: [1](https://discord.com/channels/731205301247803413/1138467653552451606/1257016707311075378), [2](https://discord.com/channels/731205301247803413/1138467653552451606/1259586315511533741).
- [ ] https://github.com/ArchipelaGOAL/Archipelago/issues/10 (Current: Default: N/A. Sync with yaml: N/A)
- [x] ~~https://github.com/ArchipelaGOAL/Archipelago/issues/12 (Current: Default: N/A. Sync with yaml: N/A)~~
- [x] https://github.com/ArchipelaGOAL/Archipelago/issues/22 (Current: Default: Gol and Maia's Precursor robot. Sync with yaml: First connect)
- [ ] https://github.com/ArchipelaGOAL/Archipelago/issues/30 (Current: Default: N/A. Sync with yaml: N/A)
- [x] Power Cell requirements settings. (Default: Heat Shield: 20. Levitation Machine: 45. Upgraded Heat Shield: 72)
- [x] Traps & filler items. (Probably just health down/up?) Discord: [1](https://discord.com/channels/731205301247803413/1138467653552451606/1254476100411723847).

**Comment by jacobmix** [comment]
Things it's time to close this one. Yaml options sync on first connect, and works well.
Think with how the mod launcher handles settings now it should keep vanilla settings, but maybe only if you already have OpenGoal it can pull from. Haven't tested.
This is kind of a mess anyway, and probably better for if an actual dev maintained to properly write what's, what instead of just being able to tick a box.
If people want more options they can suggest them in the Discord or make a new GitHub issue.
Right now only option for goggles in move rando, random start (not to be confused with [random checkpoints](https://www.opengoal.dev/docs/developing/modding_examples/checkpoint_randomizer/)), and traders changes is left but require more work.
